Part1
ok-technopolis-2021/Ilchenko-Andrey pull request #1
Opened 2021-10-03 21:04 UTC by sorgeligt

2021-10-19 23:25 UTC, aqus commented
Сверстано хорошо, но не расширяемо. В некоторых местах при изменении контента нужно изменять и фиксированные величины элементов. Так быть не должно, нужно рассчитывать, что контент может меняться и стилизация не должна ломаться, как, например тут 
![image](https://user-images.githubusercontent.com/5273083/138003878-162db133-5a3f-41a1-8e58-735dc9b88f0c.png)


ДОлжно быть примерно как-то так:
![image](https://user-images.githubusercontent.com/5273083/138003920-30c2bb50-b0fe-44cf-b3c5-9eeacad9f96b.png)

2021-10-19 23:27 UTC, aqus commented
для современных браузеров достаточно шрифтовых файлов с расширениями woff, woff2 и ttf (и то он может быть избыточным). Все остальный форматы для совсем старых браузеров и можно от них избавиться.

2021-10-19 23:33 UTC, aqus requested changes

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    font-family: Helvetica, sans-serif;
Параметры шрифта лучше указывать в body, для того, чтобы не указывать в каждом компоненте, а указывать лишь то, что изменилось.

Еще нужно указывать размер шрифта, которым будет отображаться основной контент, в нашем случае, можно указать 18 пикселей (как размер шрифта на кнопке)
указать интерлиньяж, он же line-height, опять же, чтобы не указывать в каждом элементе, а только там, где необходимо. Чаще всего макет рисуется так, что line-height по всему документу один, поэтому его указывают в относительных величинах, в пропорции от шрифта.
Нужно в body указать line-height, и его значение скорее всего будет около 1.15-1.2, можно поиграть со значениями и подобрать по вычисленному значению в devtools

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    font-weight: normal;
лучше указывать абсолютные значения, они интерпретируются браузерами однозначно
в данном случае размер должен быть 400

это относится и к остальным элементам с этим правилом

Вообще, это также можно указать один раз и изменять только в местах, где это необходимо, например, где нужен жирный шрифт

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    font-style: normal;
можно не указывать - по умолчанию normal

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    border-radius: 50px 50px 50px 50px;
если все углы имеют одинаковое скругление - можно указать одну величину - 50px

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    border-radius: 28px 28px 28px 28px;
аналогично, можно указать одну величину - 28px

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    width: 168px;
можно не задавать кнопке жесткие размеры, а позволить ей подстроиться под размер контента
Что, если завтра там будет длиннее слово? В этом случае оно не поместится в кнопку.

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    color: #FFFFFF;
color также можно указать в body, чтобы не указывать для каждого элемента отдельно, у нас же во всем документе шрифт белого цвета

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    font-style: normal;
аналогично, можно убрать

2021-10-19 23:33 UTC, aqus commented on site-card/styles/main.css
> +    width: 321px;
можно не ограничивать блок, пусть он будет на всю ширину, а текст в нем нужно центрировать.
Что, если завтра, туда придется написать фразу длиннее, теперь каждый раз менять ширину и высоту?

Это относится и к другим элементам, подумай, где можно убрать фиксированные размеры и задать обычное центрирование, чтобы не было проблем с изменением контента

2021-10-21 16:00 UTC, sorgeligt commented on site-card/styles/main.css
> +    color: #FFFFFF;
Теперь ситуация с расширяемостью выглядит так:
![image](https://user-images.githubusercontent.com/52414258/138314600-e974fa62-418c-48c4-b53e-7bf48be60c92.png)

2021-10-22 09:47 UTC, aqus approved these changes
1 ДЗ - 10 баллов
2 ДЗ - 9 баллов, сверстано отлично!

Реквест можно мержить.

![image](https://user-images.githubusercontent.com/5273083/138433219-c67774de-35f5-4aa8-a225-bb9005a7479c.png)

2021-10-22 10:03 UTC, merged