Part5 (TypeScript + SCSS + gulp)
ok-technopolis-2021/Ilchenko-Andrey pull request #6
Opened 2021-11-17 22:17 UTC by sorgeligt

2021-11-23 10:43 UTC, BusinessDuck commented on gulpfile.js
> +gulp.task('scripts', function () {
можно сделать и так,  а можно через плагины для роллапа, он тоже умеет тайпскрипт собирать (опционально)

2021-11-23 16:06 UTC, sorgeligt commented on gulpfile.js
> +gulp.task('scripts', function () {
У меня были поптыки, но на стороне клиента, в браузере, js собранный из нескольких ts файлов работать не хотел, поэтому решил воспользоваться другим решением.

2021-11-23 16:18 UTC, BusinessDuck commented on gulpfile.js
> +gulp.task('scripts', function () {
Из-за того, что rollup в настройках собирал файл в 'esm', нужно было 'iife', esm оставляет import ключевые слова и не объединяет файл в единый скрпт. Браузер не сумел запустить такой файл с импортами

2021-12-06 10:13 UTC, BusinessDuck requested changes

2021-12-06 10:13 UTC, BusinessDuck commented on package.json
>    "dependencies": {
это все devDependencies

2021-12-06 10:13 UTC, BusinessDuck commented on src/index.html
> +        <div style="flex: 1"></div>
чем оправдано? в стилях можно же указать

2021-12-06 10:13 UTC, BusinessDuck commented on src/scripts/app.ts
> +    inputValidateListener() {
хорошая реализация и архитектура

2021-12-06 10:13 UTC, BusinessDuck commented on src/scripts/app.ts
> +            this.saveLocalStorage();
хорошо

2021-12-06 10:13 UTC, BusinessDuck commented on src/scripts/app.ts
> +class SkillList implements ProgressList, Conserved {
За тайпскрипт бонусом, 15 баллов будет. Не хватает разделения рисования и модели. Есть контроллер, но нет вью, нужен класс SkillView, чтобы он только рисовал скилы. Либо обновлял. Добавление удаление и класс Skill должны быть в модели данных. А SkillView лишь рисует скил после ее изменений, а SkillList уже монтирует все это в DOM, удаляет и добавляет

2021-12-14 09:07 UTC, BusinessDuck commented
> https://sorgeligt.github.io/Ilchenko-Andrey/dist/index.html

Визуально и по интерфейсу приятно, однако есть болшой отступ от имени, это выглядит странно. Я бы разместил название скила над баром с процентами и сделал бары шире.

Работают все хоткеи для добавления tab,enter. Это хорошо. Анимации приятные.

2021-12-14 09:10 UTC, BusinessDuck commented on src/scripts/app.ts
> +        const value1: string = (document.getElementsByClassName(className) as
document.querySelector - препочтительнее, либо 
const inputs = document.getElementsByClassName(className);

const input1 = inputs[0];
const input2 = inputs[1];

не нужно дважды использовать селектор, можно записать результат в переменную

2021-12-14 09:12 UTC, BusinessDuck commented on src/scripts/app.ts
> +                ${skill + ":"}
XSS уязвимость? Точно так безопасно вставлять значения? Если там будет HTML код?

2021-12-14 09:12 UTC, BusinessDuck commented on src/scripts/app.ts
> +                    <div class="skills-list__progress-done" style="width: ${percent}%">
Просто для справки еще есть альтернативный подход через теплейты https://developer.mozilla.org/ru/docs/Web/HTML/Element/template

2021-12-14 09:14 UTC, BusinessDuck requested changes
Мне не хватило разделений на классы, все слишком кучно для объектной реализации, модель и визуальная часть смешаны очень плотно.

Сейчас в основном применяется в разработке реактивный подход. Это когда состояние модели описано отдельно, а UI изменяется в зависимости от изменения модели. То есть у тебя есть массив данных в нашем случае это скилы, в него добавляются или удаляются скилы, и в зависимости от вида манипуляции с моделью DOM реагирует на это и перестраивается, вот ниже пример как этого можно добиться. Однако будет ряд трудностей, во первых не понятно как грамотно перерисовывать содержимое, потому что может удалиться элемент в середине, и как-то нужно вычислить, какой это элемент и удалить его точечно, также элемент может добавиться в конец или в начало (не в нашем случае а в общем). Все эти перерисовки сложно управляемы. Эту задачу решают фреймоврки как раз.

В общем и целом, реактивных подход позволяет хранить данные модели отдельно, тем самым получая к ним доступ из любых мест приложения и делая его более гибким. Для отслеживания изменений в модели чаще всего используется паттерн Observer, ссылка и описание ниже.

Вот еще несколько примеров реализации от меня
```typescript
export class Skill {
    constructor(readonly name: string, readonly value: number) {}
}

export class SkillList {
    private list: Array<Skill>;

    constructor() {
        this.list = [];
    }

    add(skill: Skill) {
        this.list.push(skill);
    }

    remove(skill: Skill) {
        this.list.splice(this.list.indexOf(skill), 1);
    }
}

export class SkillView {
    constructor(private skill: Skill) {}

    render() {
        return this.HTML(`<div class="skill">${this.skill.name}<span>${this.skill.value}</span></div>`);
    }

    private HTML(str: string) {
        // @ts-ignore
        return repalceHtmlEntities(str);
    }
}

export class SkillListView {
    private list: Array<SkillView>;

    render() {
        return this.list.map(skill => skill.render()).join('');
    }
}

export class SkillListController {
    private skillList: SkillList;
    private skillListView: SkillListView;

    constructor(private target: Element) {...}

    addSkill(...) {
        // ...
        const skill = new Skill('123', 33);
        this.skillList.add(skill);
        this.target.innerHTML = this.skillListView.render();
    }
}

// index.ts

const target = document.querySelector('.target');
const skillController = new SkillListController(target);

// В идеале вообще использовать Observer Pattern

// index2.ts
const target = document.querySelector('.target');
const model = new SkillList();
const skillController = new SkillListController(target, model);

function addSkill() {
    model.push({ name: 'asdf', value: 33 });
}

function removeSkill(idx) {
    model.removeSkill(idx);
}

// И где-то внутри контроллера скилов
// Мы подписались на изменения модели, то есть при добавлении и удалении элемента вызовется коллбек. Паттерн 
 Observer можно посмотреть тут
https://monsterlessons.com/project/lessons/observer-pattern-v-javascript
this.model.subscribe((model => {});
```

2021-12-18 11:59 UTC, BusinessDuck approved these changes
Что понравилось:
1) Импорты и разделение файлов
2) Самобытность реализации
3) Подзод к сборке явно сделан с умом используется browserify для сервинга
4) Тайпскрипт
5) Есть локал сторейдж

Что не понравилось
1) Нет защиты от XSS 
2) Не нравится класс SkillListListeners, выглядит так что это в целом задача для контроллера и в класс это нет смысла выделять, можно просто в контроллере проставить либо сделать утилитарную функцию которая будет добавлять удалять листенеры.

2021-12-18 22:29 UTC, merged